### PR TITLE
Updated existing entries

### PR DESCRIPTION
**Pull request by Spiker985**
Added table format and alphabetized entries for a (hopefully) easier time for newcomers to begin contributing

### CODE REVIEW

**Review by confused-Techie — APPROVED** [review]
This looks fantastic, while it can become a tad small, lets hope thats not present when viewing on the web. I think it includes just the right amount of data, but if needed we could prune the stars section. Otherwise great work!

But I'll go ahead and wait for another review before merging, or before someone else is able to.

**Comment by Spiker985** [comment]
The other thing we might be able to do, depending in GitHub's markdown
supports it, is use the `<details>` html tags. They allow for collapsible
sections

**Review by autumnblazey — APPROVED** [review]
I do believe github can do `<details>`, mmhm

Doing a quick scan from my computer, it all seem good. The badges do look a bit tiny, but that's been discussed in the discord server before and I'm pretty sure we're all aware of that

I think I will approve it now, but just keep in mind it was only a quick look, in case someone wants to do a more close inspection / wait for me to do one tomorrow I suppose

**Comment by confused-Techie** [comment]
> The other thing we might be able to do, depending if GitHub's markdown supports it, is use the `<details>` html tags. They allow for collapsible sections

In that case if anyone does report it as being problematic we can look at that, since at least for me I feel like its valuable to have all the data available quickly at a glance.

**Review by kaosine — CHANGES_REQUESTED** [review]
My only thing is I'd suggest a link “bar” at the top. Just because of how large it is (and probably replicate it above each section tbh). Just being links to each section, so it's easy to jump around.

**Comment by Spiker985** [comment]
> My only thing is I'd suggest a link “bar” at the top. Just because of how large it is (and probably replicate it above each section tbh). Just being links to each section, so it's easy to jump around.

What about if we point out GitHub's built-in feature for Table of Contents referenced [here](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/)?

Saves us having to add more than we need to. It automatically changes with the content whenever anyone updates anything, and it likely more nicely presented than anything we could easily make in the markdown directly.

image

**Comment by confused-Techie** [comment]
@Spiker985 Totally forgot about that one. But I'd be fine with taking advantage of it, with maybe a small blurb at the top reminding users its exists and is intended to be used here.

**Comment by kaosine** [comment]
> @kaosine What about if we point out GitHub's built-in feature for Table of Contents referenced [here](https://github.blog/changelog/2021-04-13-table-of-contents-support-in-markdown-files/)?
> 
> Saves us having to add more than we need to. It automatically changes with the content whenever anyone updates anything, and it likely more nicely presented than anything we could easily make in the markdown directly.
> 
> image
> 

Or that I guess. Just want to make things as simple as possible to jump around. This could also go in the docs repo too tbh that or as a page on the website. Wherever it fits that is....I need to get back to work on those when I figure out the whole case situation for my desktop.....

**Comment by Spiker985** [comment]
@kaosine Perfect, if you accept/mark complete the changes, I think someone else can merge the PR, and then, if we don't have any additional changes on the `repo-docs` branch we can rebase the branch from main (to pull the branch history up-to-date with the current `main` HEAD), then merge to main.

**Comment by confused-Techie** [comment]
Talked to @kaosine on the Discord Server, and they approve the changes here, so as suggested I'll rebase and merge. Thanks for the contribution @Spiker985

**Pull request merged**
