### PR TITLE
Create `OPEN_COLLECTIVE.md`

### PR DESCRIPTION
**Pull request by confused-Techie**
Currently our Open Collective Configuration is rather default, and like we have said many times we need to improve it.

Using this document allows a way for us to track changes to our open collective instance, all while ensuring everyone is able to take a look at it, and modify it as needed as a team rather than an individual.

Any future changes to our Open Collective profile should go through this document and a PR first and only once this is merged then should our actual Open Collective Profile be modified.

Please let me know what you think, if anything should be changed or edited.

---

I've tried to break down each section of our profile as a header, with a short description of what that section is below it.

### CODE REVIEW

**Comment by kaosine** [comment]
From last nights discussion this is the current layout but is up for debate from there: 
image

As well we need to establish what tiers we want on there beyond the default $5, $100, and flexible donations. As well there are options to label the tiers as such:

- generic tier
- membership (recurring)
- service (support)
- product (merch)
- donation(gift)

As well, these would likely be the same tiers in our GHS if we can get that approved. We just need to figure out how we want this to look, what to call our tiers, and how we want to structure these tiers. Especially once we can start affording to sell merch and everything else. There's also the option in OC to accept crypto if we really wanted to, but I highly doubt it.

**Comment by confused-Techie** [comment]
@kaosine This PR covers everything youve said about our tier system. As in what to call them or what other tiers ro include. That was one of the major driving factors in creating this PR

**Review by kaosine — APPROVED** [review]
Going to go ahead and approve this, though probably could be a generic financial setup doc. Since we have GHS and there may be others down the line.

**Comment by confused-Techie** [comment]
Alright this has been open for some time, with approval I'll go ahead and merge this one, and make the necessary changes to our Open Collective Instance

**Pull request merged**
