### PR TITLE
Pulsar specific docs archive/migration

### PR DESCRIPTION
**Pull request by softcode589**
> *Note: This is a draft so that this could not be merged until the actual migration happens.*

This PR does Pulsar-specific docs archiving/migration for Pulsar-specific documents. I have copied the same note from the CONTRIBUTING-DURING-START doc to make it easier for the FAQ and REPOS docs.

### CODE REVIEW

**Comment by softcode589** [comment]
Should I use this as a discussion thread for migration? If not I could open a discussion.

**Comment by softcode589** [comment]
@pulsar-edit/documentation Are you really not gonna review this PR?

**Comment by confused-Techie** [comment]
> @pulsar-edit/documentation Are you really not gonna review this PR?

I was waiting to review while its a draft, if you'd like more input from the team may be best to mark that its ready for review

**Comment by softcode589** [comment]
> > @pulsar-edit/documentation Are you really not gonna review this PR?
> 
> I was waiting to review while its a draft, if you'd like more input from the team may be best to mark that its ready for review

Well that was used to block people from merging until the actual migration happens, as noted in the description.

**Comment by confused-Techie** [comment]
This style of changing our files is currently being discussed over at #58 and ideally once that reaches some sort of conclusion, we can know if modifying these documents in this way, is our plan going forward. Sorry about waiting so long for review on this PR, as we needed to determine the plan of action going forward.

As always thanks for the contribution!

**Comment by confused-Techie** [comment]
Since it seems this change is one that's not happening anytime soon, I'll go ahead and close this PR.

I apologize it isn't being merged but appreciate the contribution as always! If we do end up moving in this direction in the future, the work will still be there for us to reuse

**Pull request closed without merging**
